### PR TITLE
Fixed typos in Theorem 4.10.

### PR DESCRIPTION
**Pull request by mctague434**

### CODE REVIEW

**Comment by boazbk** [comment]
While the -1 might be a true statement, I prefer to keep the simpler statement of the theorem as is, even if the true bound is a little stronger.

**Comment by mctague434** [comment]
It's not that I think the statement needs the better bound. It's that the weaker bound makes the proof harder to check. You can't prove the inductive step using that bound. "Which solves for ..." isn't really how inductive proofs should be written.

**Comment by mctague434** [comment]
Also, there certainly are typos in the pseudo-code.

**Comment by boazbk** [comment]
OK tried to make some changes (might not have been reflected in the compile) - please take a look and if there are still problems please open an issue (since I think this proof is not as well written and might need extra polish, I'd rather do the edits myself). 
Thanks!!

**Pull request closed without merging**
