### PR TITLE
Fixed misc. typos

### PR DESCRIPTION
**Pull request by mctague434**

### CODE REVIEW

**Comment by mctague434** [comment]
Sorry I think I've accidentally resubmitted my modification to Theorem. 4.10 you didn't like. Please disregard that.

**Comment by boazbk** [comment]
Is it possible for you to edit it back to the original it so I can accept the whole pull request? Thanks!

**Comment by mctague434** [comment]
No problem. I think I've managed to do that.

**Comment by boazbk** [comment]
Thanks!!

**Pull request merged**
