### PR TITLE
some minor suggested edits to Ch 1

### PR DESCRIPTION
**Pull request by evansuva**

### CODE REVIEW

**Comment by boazbk** [comment]
Thanks! I haven't been super consistent about it, but am trying to maintain the following notation:

I use lower case letters such as f for finite functions (e.g.  mapping {0,1}^n to {0,1}) and upper case letters such as F for infinite functions (e.g., mapping {0,1}^* to {0,1}  - corresponding to languages).

**Comment by boazbk** [comment]
BTW I am still learning the GitHub interface - my comments were supposed to correspond to specific commits, but I don't think it works this way

**Comment by evansuva** [comment]
> The form of references is [secbigohnotation]{.ref} rather than #secbigohnotation{.ref}
> Can you change this? thanks!

I think I've fixed this now (but I also find github's interface on this quite confusing)...

**Comment by evansuva** [comment]
> I think I'll just drop it then and keep the second quote. (I originally also had a quote from von Neumann but I dropped it since I thought it might seem discouraging to students..)

Yes, it would have been better if the quote was from Du Bois, but alas, no.  I like this von Neumann quote for setting up a chapter on definitions, "There's no sense in being precise when you don't even know what you're talking about." (but not, "In mathematics you don't understand things, you just get used to them.", if that was that might be demoralizing to students).

**Comment by boazbk** [comment]
Thank you! Merged it!

**Pull request merged**
