### PR TITLE
Tex building

### PR DESCRIPTION
**Pull request by ChristianMay21**
I want to tackle those footnote html bugs, so I've been working on getting the html rendered on my system. While I do that, I've added some scripts and such that currently should allow anyone to render the markdown into latex  (`make all-tex`), and when I'm done allow them to render it into the html. I've made sure to do this in such a way that I do not believe it will interfere with your localized setup - all the changes I've made are added "on top of" what's already there. Y

## acknowledgments.md
Added my name, corrected a small error in the alphabetical order

## lec_02
I'm not sure why this is coming up on the changes - lec_02 was tweaked in my previous pull request, but the changes here seem to show GitHub thinking that the previous version of the file is still "active." This is strange, as I manually checked both my version and the version on the master branch of this repo, and they are the same. I'm not sure if GitHub would allow you to just discard this change specifically, but if so maybe do that?

## scripts .gitignore
When building tex using `make all-tex`, the scripts generate logs which are output into the `scripts` folder. This tells git to ignore those. 

## LaTeXAccents.py
This file is required for line 39 in book-filter.py to work. It's probably in your local setup somewhere? Best I can tell there's no module version of LaTexAccents, so it has to be included locally.

## scripts/__pycache__/.gitignore 
When running LaTeXAccents.py, it creates a folder for a cache and creates a cache inside it. I added this folder, and a .gitignore so that the cache is ignored by git. 

## scripts/auxtoyaml.py 
Fixed a minor typo in a comment

## binaries, latex, latex-book, html, content
These all appear to be folders hardwired into the makefile and related files which are used to contain build artifacts. I therefore included them, and an appropriate .gitignore to ignore these build artifacts, to pre-empt "this folder does not exist" errors.

## scripts/readme.md
I added some stuff to the readme in the scripts file to help anyone else along who might choose to get these scripts up and running on their systems - figuring out a brand new software system is never easy, and a lot of work on my part went into figuring out what connected with what, what modules had to be installed, what folders were missing, etc. Where I could, I simply added folders/files so that future software adventurers didn't have to worry about these issues. Where I could not, I provided instructions in this readme. It also gives some background on the work I'm currently trying to do on the package, in case anyone else wants to tackle that task.

## setup.py
This python scripts makes some untracked copies of files to be where the makefile and python scripts expect them to be, to prevent "file does not exist" errors.

Let me know if there are any changes you'd like me to make. **Also**, any guidance on how to get the html up and running would be greatly appreciated - even just a brief overview of the processes involved in rendering would be greatly appreciated.

### CODE REVIEW

**Comment by boazbk** [comment]
hi
I think the right thing to do, which I never had the time to do, is to create a separate package/project that contains everything that’s needed to build a book from markdown and can be used for this book as well as others. If you are interested in helping with that then I’d be happy to share with you all the setup I’m currently using.

**Comment by ChristianMay21** [comment]
Sure! I'd love to do that. If you'd like to email me anything you may do so at cjm8ye at virginia dot edu

**Comment by boazbk** [comment]
Btw I came across these projects
https://bookdown.org/home/

https://github.com/rust-lang/mdBook

I wonder if there is something we can learn from them

**Comment by boazbk** [comment]
Is it OK if I close this pull request since we'll move this work to the new repository?

**Pull request closed without merging**
