### PR TITLE
Miswording

### PR DESCRIPTION
**Pull request by ramkarri7**

### CODE REVIEW

**Comment by boazbk** [comment]
Can you try combining the pull requests together? Thanks

**Comment by ramkarri7** [comment]
Hi I tried forking the repository but then it keeps requesting to mine. How
should I combine them?

**Comment by boazbk** [comment]
I’m not an expert but can try searching for how to do it later today. I
think the idea is that you fork, make several commits and then post a pull
request combining them - you can look at some of the closed pull requests
of Christian May as examples

**Comment by ramkarri7** [comment]
Sounds good I’ll look into it! Also, is there anything other than simple
grammar that could be of contribution to the textbook? I would love to help!

**Comment by boazbk** [comment]
Here's an example of a pull request combining several commits
https://github.com/boazbk/tcs/pull/429
The grammar help is super useful - thanks!
Aside from that, if you find things confusing or unclear while you read,
please don't hesitate to open an issue!
Boaz

**Pull request merged**
