### PR TITLE
Update lec_02_representation.md

### PR DESCRIPTION
**Pull request by ramkarri7**
should be homework I believe.

### CODE REVIEW

**Comment by boazbk** [comment]
Thanks! Can you try to put together several edits in one pull request?

**Comment by ramkarri7** [comment]
Hi,

I have already made the commits. How should I combine them into one
request? Will I need to manually do them all?

**Comment by boazbk** [comment]
Do t worry about these ones - this is just for the future

**Comment by ramkarri7** [comment]
Thanks! I will keep that in mind. Sorry for having to accept each one
manually I know there are a lot. I will combine the commits next time I
just figured out how to do so.

Thanks,
Ram!

**Pull request merged**
